### PR TITLE
Follow up v1.4.1

### PR DESCRIPTION
**Pull request by joowon-byun**
# Changes
* Updated the dependency version to match those at @truffle/hdwallet-provider@1.4.1 (refer : [package.json](https://github.com/trufflesuite/truffle/blob/%40truffle/hdwallet-provider%401.4.1/packages/hdwallet-provider/package.json) and [yarn.lock](https://github.com/trufflesuite/truffle/blob/%40truffle/hdwallet-provider%401.4.1/yarn.lock))
     * The versions are same except for `mocha`. Updated `mocha` to the latest version, `v9.0.2` to fix a dependency alert.
* Modified code and README to match v1.4.1 (comparison refer : https://github.com/trufflesuite/truffle/compare/@truffle/hdwallet-provider@1.2.0...@truffle/hdwallet-provider@1.4.1)
* Applied prettier and eslint (refer : [package.json](https://github.com/trufflesuite/truffle/blob/%40truffle/hdwallet-provider%401.4.1/package.json) and [hdwallet/package.json](https://github.com/trufflesuite/truffle/blob/%40truffle/hdwallet-provider%401.4.1/packages/hdwallet-provider/package.json))

# Tests
* Passed all unit tests (19 passing (337ms))
* Migrated and made transaction to Baobab network.

### CODE REVIEW

**Review by baerae-colin — APPROVED** [review]
LGTM. Thanks!

**Comment by joowon-byun** [comment]
@kjhman21
I deleted a line to use the gas value from `truffle-config.js`. (Deleted code : `txParams.gas = "0x500000";`)
Previously, truffle code reset the gas value to `0x0` when using caver. Didn't make a closer look at this problem, but it seems to be fixed in the new version.

Everything else from [4729d1c](https://github.com/klaytn/truffle-hdwallet-provider-klaytn/pull/5/commits/4729d1cff7c7d58c6dd13e42df33c955344d3aae?file-filters%5B%5D=.ts) is just lint.

**Comment by baerae-colin** [comment]
@winnie-byun 
> it seems to be fixed in the new version.

Will you fix it in the next version?

**Comment by joowon-byun** [comment]
@kjhman21 I put back the code :)
Just lint is left after you approved.

**Comment by joowon-byun** [comment]
@kjhman21 Do you think we are ready to merge, or should I make an modification?

**Comment by baerae-colin** [comment]
@winnie-byun 👍  Go ahead!

**Comment by aidan-kwon** [comment]
@hoiJuwon 좋은 의견 감사합니다. 제안 주신 방법으로 수정하겠습니다.

**Comment by hoiJuwon** [comment]
> @hoiJuwon 좋은 의견 감사합니다. 제안 주신 방법으로 수정하겠습니다.

@aidan-kwon 아직 반영이 안된거 같은데 이유가 있을까요 ?

**Comment by aidan-kwon** [comment]
@hoiJuwon 다음과 같이 master branch가 수정되었는데, 혹시 여전히 문제를 겪고 있으신가요? https://github.com/klaytn/truffle-hdwallet-provider-klaytn/blob/5284e5182d0139fdf12d0617a2079bdbd544f2cc/src/index.ts#L150-L151

**Comment by hoiJuwon** [comment]
@aidan-kwon 아 확인을 잘못했네요. 죄송합니다.

**Comment by aidan-kwon** [comment]
@hoiJuwon 지속적으로 관심 가져주셔서 감사합니다.

**Pull request merged**
